-- Table: public.all_players

-- DROP TABLE IF EXISTS public.all_players;

CREATE TABLE IF NOT EXISTS public.all_players
(PLAYER_ID VARCHAR(255) PRIMARY KEY,
	BIRTH_STATE VARCHAR(255) NULL,
	STATUS VARCHAR(255) NULL,
	INJURY_START_DATE VARCHAR(255) NULL,
	BIRTH_DATE VARCHAR(255) NULL,
	SEARCH_FULL_NAME VARCHAR(255) NULL,
	INJURY_NOTES VARCHAR(255) NULL,
	TEAM VARCHAR(255) NULL,
	FANTASY_DATA_ID VARCHAR(255) NULL,
	POSITION VARCHAR(255) NULL,
	ROTOWORLD_ID VARCHAR(255) NULL,
	STATS_ID VARCHAR(255) NULL,
	DEPTH_CHART_ORDER VARCHAR(255) NULL,
	SPORTRADAR_ID VARCHAR(255) NULL,
	DEPTH_CHART_POSITION VARCHAR(255) NULL,
	HASHTAG VARCHAR(255) NULL,
	FIRST_NAME VARCHAR(255) NULL,
	SEARCH_LAST_NAME VARCHAR(255) NULL,
	SEARCH_RANK VARCHAR(255) NULL,
	SEARCH_FIRST_NAME VARCHAR(255) NULL,
	BIRTH_CITY VARCHAR(255) NULL,
	PANDASCORE_ID VARCHAR(255) NULL,
	FANTASY_POSITIONS text[] NULL,
	COLLEGE VARCHAR(255) NULL,
	LAST_NAME VARCHAR(255) NULL,
	ESPN_ID VARCHAR(255) NULL,
	INJURY_STATUS VARCHAR(255) NULL,
	METADATA VARCHAR(255) NULL,
	AGE VARCHAR(255) NULL,
	YAHOO_ID VARCHAR(255) NULL,
	HEIGHT VARCHAR(255) NULL, 
 	NUMBER VARCHAR(255) NULL,
	BIRTH_COUNTRY VARCHAR(255) NULL,
	WEIGHT VARCHAR(255) NULL,
	INJURY_BODY_PART VARCHAR(255) NULL,
	FULL_NAME VARCHAR(255) NULL,
	HIGH_SCHOOL VARCHAR(255) NULL,
	SWISH_ID VARCHAR(255) NULL,
	GSIS_ID VARCHAR(255) NULL,
	ACTIVE BOOL NULL,
	NEWS_UPDATED VARCHAR(255) NULL,
	SPORT VARCHAR(255) NULL,
	PRACTICE_DESCRIPTION VARCHAR(255) NULL,
	YEARS_EXP VARCHAR(255) NULL,
	ROTOWIRE_ID VARCHAR(255) NULL,
	PRACTICE_PARTICIPATION VARCHAR(255) NULL)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.all_players
    OWNER to postgres;