# Generated by Django 4.2.1 on 2023-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adp",
            fields=[
                (
                    "player_id",
                    models.CharField(
                        db_column="player_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("team", models.CharField(max_length=10)),
                ("adp", models.FloatField(null=True)),
                ("bye", models.IntegerField()),
                ("draft_position", models.IntegerField()),
                ("ffcalc_id", models.CharField(max_length=10)),
                ("adp_formatted", models.FloatField()),
                ("times_drafted", models.IntegerField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("stdev", models.FloatField()),
            ],
            options={
                "db_table": "adp",
            },
        ),
    ]
